name: Push to Another Repo

on:
  push:
    branches: [ work_flow_home ]
  workflow_dispatch:

jobs:
  push-to-external-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Configure Git credentials
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${TARGET_REPO_TOKEN}@github.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials

      - name: Push to external repo
        run: |
          echo "Attempting push with configured credentials..."
          git push --force "https://github.com/ijasah/home.git" HEAD:main