name: Push to Another Repo

on:
  push:
    branches: [ work_flow_home ]
  workflow_dispatch:

jobs:
  push-to-external-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if token is set
        run: |
          if [ -z "${TARGET_REPO_TOKEN}" ]; then
            echo "TOKEN NOT SET"
            exit 1
          else
            echo "TOKEN IS SET"
          fi
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}

      - name: Push to external repo
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git remote remove external || true
          git remote add external https://x-access-token:${TARGET_REPO_TOKEN}@github.com/ijasah/home.git
          git push --force external HEAD:main